const SoftwareData = [
    {
        id: 1,
        name: "Spotify",
        discription: "Spotify is a digital music, podcast, and video service that gives you access to millions of songs and other content from creators all over the world. Basic functions such as playing music are totally free, but you can also choose to upgrade to Spotify Premium.",
        image1: "https://storage.googleapis.com/pr-newsroom-wp/1/2023/01/AppleCompetition-FTRHeader_V2-1440x733.png",
        logo: "https://i.redd.it/zupv7p7bvmo51.png",
        windows: 'https://download.scdn.co/SpotifySetup.exe',
        linux: 'https://www.spotify.com/de-en/download/linux/',
        mac: 'https://download.scdn.co/SpotifyInstaller.zip',
        company: "Spotify AB",
        company_logo: "https://play-lh.googleusercontent.com/cShys-AmJ93dB0SV8kE6Fl5eSaf4-qMMZdwEDKI5VEmKAXfzOqbiaeAsqqrEBCTdIEs",
    },
    {
        id: 2,
        name: "Visual Studio Code",
        discription: "Visual Studio Code, also commonly referred to as VS Code, is a source-code editor made by Microsoft with the Electron Framework, for Windows, Linux and macOS.",
        image1: "https://storage.googleapis.com/pr-newsroom-wp/1/2023/01/AppleCompetition-FTRHeader_V2-1440x733.png",
        logo: "https://code.visualstudio.com/opengraphimg/opengraph-blog.png",
        windows: 'https://az764295.vo.msecnd.net/stable/abd2f3db4bdb28f9e95536dfa84d8479f1eb312d/VSCodeUserSetup-x64-1.82.2.exe',
        linux: 'https://code.visualstudio.com/docs/setup/linux',
        mac: 'https://az764295.vo.msecnd.net/stable/abd2f3db4bdb28f9e95536dfa84d8479f1eb312d/VSCode-darwin-universal.zip',
        company: "Microsoft",
        company_logo: "https://yt3.googleusercontent.com/ytc/AOPolaSxX7E6tUlp4fiXj6SsG7C-RfhuE0pz73t3FbwDVQ=s900-c-k-c0x00ffffff-no-rj",
    },
    {
        id: 3,
        name: "CCleaner",
        discription: "CCleaner is a small, effective optimization app designed to reclaim storage space of your devices. It does this by cleaning out the 'junk' that has accumulated over time. Junk could be: Temporary or deleted files.",
        image1: "https://storage.googleapis.com/pr-newsroom-wp/1/2023/01/AppleCompetition-FTRHeader_V2-1440x733.png",
        logo: "https://oceanofdmg.com/wp-content/uploads/2021/12/CCleaner-Professional-2022-for-Mac-Free-Download-OceanofDMG.com_.jpg",
        windows: 'https://bits.avcdn.net/productfamily_CCLEANER/insttype_FREE/platform_WIN_PIR/installertype_ONLINE/build_RELEASE/cookie_mmm_ccl_003_999_a7i_m',
        linux: 'https://example.com/',
        mac: 'https://download.ccleaner.com/mac/CCMacSetup209.dmg',
        company: "Avast, Gen Digital",
        company_logo: "https://upload.wikimedia.org/wikipedia/en/4/4a/CCleaner_logo_2013.png",
    },
];

export default SoftwareData;
